# Site settings
title: Freifunk München
email: 
description: "Die nichtkommerzielle Initiative für den Aufbau freier (Funk-)Netzwerke in München"
baseurl: ""
url: "https://ffmuc.net/"
twitter_username: FreifunkMUC
github_username:  FreifunkMUC

# Build settings
markdown: kramdown
permalink: pretty

# Custom headers
webrick:
  headers:
    Content-Security-Policy: default-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' 'self'  ; connect-src wss://ffmuc.net 'self' firmware.ffmuc.net; img-src 'self' data: blob: filesystem:  ; style-src 'self' 'unsafe-inline' 'unsafe-eval' ;    media-src 'self' ; font-src 'self' data: blob: filesystem; frame-src 'self'; 
    My-Other-Header: My-Other-Value
